### ISSUE TITLE
Change background while running

### ISSUE THREAD

**Issue by ShaddyDC** [The-Aquila-Network-Community/osu-ingame-background-changer#1]
Whilst the program is already great as it is, it would be nice to change the background on the fly without having to restart everything. So as not to add any additional windows or stuff that runs all the time and takes up desktop space and clusters the task bar, I'd recommend to open the file selection menu via a hotkey.
Well, this feature isn't necessarily needed, but it would be pretty neat to have. :)

**Comment by holly-hacker** [comment]
You should be able to inject the DLL again and select another image, but I'll try to add a hotkey later to bring up the menu again.

**Comment by holly-hacker** [comment]
Added in last commit.
